service: parte2

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role: arn:aws:iam::331315825646:role/LabRole
  environment:
    TABLE_NAME: ${sls:stage}-t_todos

functions:
  hello:
    handler: functions/todoHandler.handler
    events:
    - http:
        path: /todos
        method: get
        cors: true
        integration: lambda
    - http:
        path: /todos
        method: post
        cors: true
        integration: lambda

resources:
- ${file(./resources/dynamodb-tables.yml)}

custom:
  stage: ${sls:stage}
